#!/usr/bin/env sh

echo "🔍 Running pre-commit checks..."

if ! pnpm lint; then
  echo "❌ Linting failed."
  exit 1
fi

if ! pnpm type-check; then
  echo "❌ Type checking failed."
  exit 1
fi

echo "✅ Pre-commit passed!"